import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#012d1d',
        'primary-container': '#1b4332',
        background: '#fcf9f2',
        surface: '#fcf9f2',
        'surface-bright': '#fcf9f2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ec',
        'surface-container': '#f0eee6',
        'surface-container-high': '#eae8e1',
        'surface-container-highest': '#e5e2db',
        'surface-variant': '#e5e2db',
        'surface-dim': '#dcdad3',
        'on-surface': '#1b1c18',
        'on-surface-variant': '#414844',
        'on-primary': '#ffffff',
        'on-primary-container': '#86af99',
        secondary: '#43664d',
        'secondary-container': '#c2e9c9',
        'on-secondary-container': '#486a51',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
        'surface-tint': '#3f6653',
        'inverse-primary': '#a5d0b9',
        error: '#ba1a1a',
        'auth-background': '#f8f9ff',
        'auth-surface': '#f8f9ff',
        'auth-surface-container': '#e5eeff',
        'auth-surface-container-low': '#eff4ff',
        'auth-surface-container-high': '#dce9ff',
        'auth-surface-container-highest': '#d3e4fe',
        'auth-surface-variant': '#d3e4fe',
        'auth-surface-dim': '#cbdbf5',
        'auth-on-background': '#0b1c30',
        'auth-on-surface': '#0b1c30',
        'auth-secondary': '#5c5f60',
        'auth-secondary-fixed': '#e1e3e4',
        'auth-secondary-fixed-dim': '#c5c7c8',
        'auth-inverse-on-surface': '#eaf1ff',
        'admin-background': '#f8f9ff',
        'admin-surface': '#f8f9ff',
        'admin-surface-bright': '#f8f9ff',
        'admin-surface-container': '#e5eeff',
        'admin-surface-container-low': '#eff4ff',
        'admin-surface-container-high': '#dce9ff',
        'admin-surface-container-highest': '#d3e4fe',
        'admin-surface-container-lowest': '#ffffff',
        'admin-surface-variant': '#d3e4fe',
        'admin-surface-dim': '#cbdbf5',
        'admin-on-surface': '#0b1c30',
        'admin-on-background': '#0b1c30',
        'admin-on-surface-variant': '#414844',
        'admin-outline-variant': '#c1c8c2',
        'admin-outline': '#717973',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Manrope', 'sans-serif'],
      },
      spacing: {
        gutter: '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        'level-1': '0px 4px 20px rgba(27, 67, 50, 0.04)',
        'level-2': '0px 12px 32px rgba(27, 67, 50, 0.08)',
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '600' }],
        'auth-h1': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'auth-h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'auth-h3': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'auth-body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'auth-body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'auth-label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'auth-table-data': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'admin-body-base': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'admin-body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'admin-table-data': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'admin-h1': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'admin-h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'admin-h3': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'admin-label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
